### PR TITLE
Easy to use from CLI and npm run-script

### PR DESCRIPTION
**Pull request by sanemat**
before:
./node_modules/touch/bin/touch.js FILE
after:
$(npm bin)/touch FILE

### CODE REVIEW

**Comment by isaacs** [comment]
Ah, strange, I thought that the bin was already listed.  Thanks.

Btw, in `npm run-script` commands, you can just do `touch` and it'll find the one in `node_modules/.bin`, because of `PATH` environment magic.

**Comment by isaacs** [comment]
Travis failure is unrelated.

**Comment by isaacs** [comment]
Landed on master and published.  thanks!

**Comment by sanemat** [comment]
@isaacs Thanks! :smile:

**Pull request closed without merging**
