### PR TITLE
Fix calling touch on dirs

### LINKED ISSUE #8: Error when touching directories
``` sh
$ touch node_modules/
bad touch!
/Users/mstade/dev/websdk/nap/node_modules/touch/bin/touch.js:28
      throw er
      ^

Error: EISDIR: illegal operation on a directory, open 'node_modules/'
    at Error (native)
```

Quite possibly out of scope for the module, but figured I'd report it either way.

---

I don't use this module myself, but ran into a problem with builds suddenly failing because of it. The reason is during the build, the `$PATH` variable is prepended with `node_modules/.bin`, so local executables can be conveniently used in the Makefile. Because it's prepended, `touch` takes precedence over the system `touch`, and because this module doesn't work with directories the build failed.

The builds started suddenly failing, because Travis CI started including Node 5.0 in their environment setup. This includes npm 3, which has the new flat module layout. This brought up the this module from the node_modules depths, and voila – failing builds.

Interesting little detour. :o)

It was easy enough to fix. Just changed it to append `node_modules/.bin` to `$PATH`, as opposed to prepending it:

``` makefile
PATH := $(PATH):node_modules/.bin
```

Someone else might run into the same issue, so hopefully searching will lead them here.

### PR DESCRIPTION
**Pull request by nylen**
Fixes #8 by detecting `EISDIR` and passing `fd = null` through the chain of function calls, using `options.f` (the path to the file to touch) instead if there is no open `fd`.

This code is a bit hairy so let me know if you'd like to see any additional tests.

### CODE REVIEW

**Comment by dominicbarnes** [comment]
It would be great to have this fix merged and released, as the module is currently broken for this very specific use-case that I need.

**Comment by nylen** [comment]
cc @isaacs

**Comment by lukeburns** [comment]
i could also use this fix

**Comment by nylen** [comment]
cc @isaacs

**Pull request closed without merging**
